# SPDX-FileCopyrightText: © 2017-2026 Adrian Johnston.
# SPDX-License-Identifier: MIT
# This file is licensed under the terms of the LICENSE.md file.

executable('hxexample',
	sources : ['example.cpp'],
	include_directories : hx_include_directory,
	c_args : hx_c_args,
	cpp_args : hx_cpp_args,
	link_with : libhatchet,
)
