var annotated_dup =
[
    [ "testing", "namespacetesting.html", [
      [ "Test", "classtesting_1_1Test.html", "classtesting_1_1Test" ]
    ] ],
    [ "hxallocator", "classhxallocator.html", "classhxallocator" ],
    [ "hxallocator&lt; T, hxallocator_dynamic_capacity &gt;", "classhxallocator_3_01T_00_01hxallocator__dynamic__capacity_01_4.html", "classhxallocator_3_01T_00_01hxallocator__dynamic__capacity_01_4" ],
    [ "hxarray", "classhxarray.html", "classhxarray" ],
    [ "hxbitset", "classhxbitset.html", "classhxbitset" ],
    [ "hxcondition_variable", "classhxcondition__variable.html", "classhxcondition__variable" ],
    [ "hxconsteval_delete", "classhxconsteval__delete.html", "classhxconsteval__delete" ],
    [ "hxconstexpr_list", "classhxconstexpr__list.html", "classhxconstexpr__list" ],
    [ "hxconstexpr_list_node", "classhxconstexpr__list__node.html", "classhxconstexpr__list__node" ],
    [ "hxdefault_delete", "classhxdefault__delete.html", "classhxdefault__delete" ],
    [ "hxdeque", "classhxdeque.html", "classhxdeque" ],
    [ "hxdo_not_delete", "classhxdo__not__delete.html", "classhxdo__not__delete" ],
    [ "hxexpected", "classhxexpected.html", "classhxexpected" ],
    [ "hxfalse_t", "structhxfalse__t.html", null ],
    [ "hxfile", "classhxfile.html", "classhxfile" ],
    [ "hxflat_map", "classhxflat__map.html", "classhxflat__map" ],
    [ "hxflat_map_const_value_t", "classhxflat__map__const__value__t.html", "classhxflat__map__const__value__t" ],
    [ "hxflat_map_value_t", "classhxflat__map__value__t.html", "classhxflat__map__value__t" ],
    [ "hxflat_set", "classhxflat__set.html", "classhxflat__set" ],
    [ "hxfree_list", "classhxfree__list.html", "classhxfree__list" ],
    [ "hxhandle_table", "classhxhandle__table.html", "classhxhandle__table" ],
    [ "hxhash_node_base", "classhxhash__node__base.html", "classhxhash__node__base" ],
    [ "hxhash_table", "classhxhash__table.html", "classhxhash__table" ],
    [ "hxhash_table_map_node", "classhxhash__table__map__node.html", "classhxhash__table__map__node" ],
    [ "hxhash_table_node_integer", "classhxhash__table__node__integer.html", "classhxhash__table__node__integer" ],
    [ "hxhash_table_node_string", "classhxhash__table__node__string.html", "classhxhash__table__node__string" ],
    [ "hxhash_table_node_string_literal", "classhxhash__table__node__string__literal.html", "classhxhash__table__node__string__literal" ],
    [ "hxhash_table_set_node", "classhxhash__table__set__node.html", "classhxhash__table__set__node" ],
    [ "hxkey_equal_t", "classhxkey__equal__t.html", "classhxkey__equal__t" ],
    [ "hxkey_equal_t&lt; hxarray&lt; T, capacity_ &gt; &gt;", "classhxkey__equal__t_3_01hxarray_3_01T_00_01capacity___01_4_01_4.html", "classhxkey__equal__t_3_01hxarray_3_01T_00_01capacity___01_4_01_4" ],
    [ "hxkey_equal_t&lt; hxexpected&lt; T, E_ &gt; &gt;", "classhxkey__equal__t_3_01hxexpected_3_01T_00_01E___01_4_01_4.html", "classhxkey__equal__t_3_01hxexpected_3_01T_00_01E___01_4_01_4" ],
    [ "hxkey_equal_t&lt; hxptr&lt; T, deleter_t_ &gt; &gt;", "classhxkey__equal__t_3_01hxptr_3_01T_00_01deleter__t___01_4_01_4.html", "classhxkey__equal__t_3_01hxptr_3_01T_00_01deleter__t___01_4_01_4" ],
    [ "hxkey_equal_t&lt; hxref&lt; T &gt; &gt;", "classhxkey__equal__t_3_01hxref_3_01T_01_4_01_4.html", "classhxkey__equal__t_3_01hxref_3_01T_01_4_01_4" ],
    [ "hxkey_equal_t&lt; hxvector&lt; T, capacity_x_ &gt; &gt;", "classhxkey__equal__t_3_01hxvector_3_01T_00_01capacity__x___01_4_01_4.html", "classhxkey__equal__t_3_01hxvector_3_01T_00_01capacity__x___01_4_01_4" ],
    [ "hxkey_equal_t&lt; T, hxenable_if_t&lt; hxis_string&lt; T &gt;()&gt; &gt;", "classhxkey__equal__t_3_01T_00_01hxenable__if__t_3_01hxis__string_3_01T_01_4_07_08_4_01_4.html", "classhxkey__equal__t_3_01T_00_01hxenable__if__t_3_01hxis__string_3_01T_01_4_07_08_4_01_4" ],
    [ "hxkey_hash_t", "classhxkey__hash__t.html", "classhxkey__hash__t" ],
    [ "hxkey_hash_t&lt; hxarray&lt; T, capacity_ &gt; &gt;", "classhxkey__hash__t_3_01hxarray_3_01T_00_01capacity___01_4_01_4.html", "classhxkey__hash__t_3_01hxarray_3_01T_00_01capacity___01_4_01_4" ],
    [ "hxkey_hash_t&lt; hxexpected&lt; T, E_ &gt; &gt;", "classhxkey__hash__t_3_01hxexpected_3_01T_00_01E___01_4_01_4.html", "classhxkey__hash__t_3_01hxexpected_3_01T_00_01E___01_4_01_4" ],
    [ "hxkey_hash_t&lt; hxptr&lt; T, deleter_t_ &gt; &gt;", "classhxkey__hash__t_3_01hxptr_3_01T_00_01deleter__t___01_4_01_4.html", "classhxkey__hash__t_3_01hxptr_3_01T_00_01deleter__t___01_4_01_4" ],
    [ "hxkey_hash_t&lt; hxref&lt; T &gt; &gt;", "classhxkey__hash__t_3_01hxref_3_01T_01_4_01_4.html", "classhxkey__hash__t_3_01hxref_3_01T_01_4_01_4" ],
    [ "hxkey_hash_t&lt; hxvector&lt; T, capacity_x_ &gt; &gt;", "classhxkey__hash__t_3_01hxvector_3_01T_00_01capacity__x___01_4_01_4.html", "classhxkey__hash__t_3_01hxvector_3_01T_00_01capacity__x___01_4_01_4" ],
    [ "hxkey_hash_t&lt; T, hxenable_if_t&lt; hxis_string&lt; T &gt;()&gt; &gt;", "classhxkey__hash__t_3_01T_00_01hxenable__if__t_3_01hxis__string_3_01T_01_4_07_08_4_01_4.html", "classhxkey__hash__t_3_01T_00_01hxenable__if__t_3_01hxis__string_3_01T_01_4_07_08_4_01_4" ],
    [ "hxkey_less_t", "classhxkey__less__t.html", "classhxkey__less__t" ],
    [ "hxkey_less_t&lt; hxarray&lt; T, capacity_ &gt; &gt;", "classhxkey__less__t_3_01hxarray_3_01T_00_01capacity___01_4_01_4.html", "classhxkey__less__t_3_01hxarray_3_01T_00_01capacity___01_4_01_4" ],
    [ "hxkey_less_t&lt; hxvector&lt; T, capacity_x_ &gt; &gt;", "classhxkey__less__t_3_01hxvector_3_01T_00_01capacity__x___01_4_01_4.html", "classhxkey__less__t_3_01hxvector_3_01T_00_01capacity__x___01_4_01_4" ],
    [ "hxkey_less_t&lt; T, hxenable_if_t&lt; hxis_string&lt; T &gt;()&gt; &gt;", "classhxkey__less__t_3_01T_00_01hxenable__if__t_3_01hxis__string_3_01T_01_4_07_08_4_01_4.html", "classhxkey__less__t_3_01T_00_01hxenable__if__t_3_01hxis__string_3_01T_01_4_07_08_4_01_4" ],
    [ "hxlist", "classhxlist.html", "classhxlist" ],
    [ "hxlist_node", "classhxlist__node.html", "classhxlist__node" ],
    [ "hxmemory_manager_stats", "classhxmemory__manager__stats.html", "classhxmemory__manager__stats" ],
    [ "hxminmax_result", "classhxminmax__result.html", "classhxminmax__result" ],
    [ "hxmutex", "classhxmutex.html", "classhxmutex" ],
    [ "hxnil_t", "classhxnil__t.html", "classhxnil__t" ],
    [ "hxptr", "classhxptr.html", "classhxptr" ],
    [ "hxradix_sort_key", "classhxradix__sort__key.html", "classhxradix__sort__key" ],
    [ "hxrandom", "classhxrandom.html", "classhxrandom" ],
    [ "hxrange", "classhxrange.html", "classhxrange" ],
    [ "hxref", "classhxref.html", "classhxref" ],
    [ "hxsettings_t", "structhxsettings__t.html", "structhxsettings__t" ],
    [ "hxslot_map", "classhxslot__map.html", "classhxslot__map" ],
    [ "hxsystem_allocator_scope", "classhxsystem__allocator__scope.html", "classhxsystem__allocator__scope" ],
    [ "hxtask", "classhxtask.html", "classhxtask" ],
    [ "hxtask_dag_node", "classhxtask__dag__node.html", "classhxtask__dag__node" ],
    [ "hxtask_queue", "classhxtask__queue.html", "classhxtask__queue" ],
    [ "hxthread", "classhxthread.html", "classhxthread" ],
    [ "hxthread_local", "classhxthread__local.html", "classhxthread__local" ],
    [ "hxtrue_t", "structhxtrue__t.html", null ],
    [ "hxunique_lock", "classhxunique__lock.html", "classhxunique__lock" ],
    [ "hxvector", "classhxvector.html", "classhxvector" ]
];