# SPDX-FileCopyrightText: © 2017-2026 Adrian Johnston.
# SPDX-License-Identifier: MIT
# This file is licensed under the terms of the LICENSE.md file.

# Type stubs for the parts of the GDB Python API used by the pretty printers.

from typing import Any, Optional, Union

class Field:
	name: Optional[str]
	type: "Type"
	is_base_class: bool

class Type:
	sizeof: int
	def fields(self) -> list[Field]: ...
	def pointer(self) -> "Type": ...
	def target(self) -> "Type": ...
	def template_argument(self, n: int) -> Any: ...

class Value:
	type: Type
	address: "Value"
	is_optimized_out: bool
	def __init__(self, val: Any) -> None: ...
	def __getitem__(self, key: Union[str, Field, int]) -> "Value": ...
	def __int__(self) -> int: ...
	def cast(self, type: Type) -> "Value": ...
	def dereference(self) -> "Value": ...

def current_objfile() -> Optional[Any]: ...
