# SPDX-FileCopyrightText: © 2017-2026 Adrian Johnston.
# SPDX-License-Identifier: MIT
# This file is licensed under the terms of the LICENSE.md file.

# Type stubs for the parts of the GDB Python API used by the pretty printers.

from typing import Any, Optional, Union

COMMAND_DATA: int
PARAM_ZUINTEGER: int

class Field:
	name: Optional[str]
	type: "Type"
	is_base_class: bool

class Inferior:
	def read_memory(self, address: int, length: int) -> memoryview: ...

class Parameter:
	value: Any
	def __init__(
		self, name: str, command_class: int, parameter_class: int,
		enum_sequence: Optional[list[str]] = ...
	) -> None: ...

class Type:
	sizeof: int
	def fields(self) -> list[Field]: ...
	def pointer(self) -> "Type": ...
	def strip_typedefs(self) -> "Type": ...
	def target(self) -> "Type": ...
	def template_argument(self, n: int) -> Any: ...

class Value:
	type: Type
	address: "Value"
	is_optimized_out: bool
	def __init__(self, val: Any) -> None: ...
	def __eq__(self, other: object) -> bool: ...
	def __getitem__(self, key: Union[str, Field, int]) -> "Value": ...
	def __int__(self) -> int: ...
	def cast(self, type: Type) -> "Value": ...
	def dereference(self) -> "Value": ...
	def string(self) -> str: ...

def current_objfile() -> Optional[Any]: ...
def selected_inferior() -> Inferior: ...
